[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Bob", email = "bo.hanson@f5.com"}]
dynamic = ["version", "description"]
